# Generated by Django 3.1.7 on 2021-03-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_auto_20210309_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='img/article'),
        ),
    ]
