# Generated by Django 3.1.7 on 2021-03-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
